-- vim.cmd [[
-- let g:airline#extensions#tabline#enabled = 1
-- let g:airline#extensions#tabline#formatter = 'default'  " f/p/file-name.js
-- let g:airline#extensions#tabline#formatter = 'jsformatter' " path-to/f
-- let g:airline#extensions#tabline#formatter = 'unique_tail' " file-name.js
-- let g:airline#extensions#tabline#formatter = 'unique_tail_improved' " f/p/file-name.js
-- let g:airline_powerline_fonts = 1
-- let g:airline#extensions#tabline#enabled = 1
-- let g:airline_theme='minimalist'
-- ]]

